services:
  web:
    build: .
    ports:
      - '5001:5000'
    volumes:
      - ./app.py:/app/app.py
    depends_on:
      - redis

  redis:
    image: redis:latest

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
