services:
  web:
    build: .
    ports:
      - '5002:5002'
    volumes:
      - ./logs:/logs
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - ./redis-data:/data

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
